apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.service.grpc }}
      targetPort: {{ .Values.service.grpc }}
      protocol: TCP
      name: grpc
  selector:
    app: {{ .Chart.Name }}
