apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
{{ if eq .Values.service.type "ClusterIP" }}
  clusterIP: {{ .Values.service.clusterIP | default "None" | quote }}
{{ end }}
  ports:
    - port: {{ .Values.service.externalRpcPort }}
      targetPort: {{ .Values.service.internalRpcPort }}
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.externalManagerRpcPort }}
      targetPort: {{ .Values.service.internalManagerRpcPort }}
      protocol: TCP
      name: managergrpc
  selector:
    app: {{ .Chart.Name }}
