replicasCount: 1
maxUnavailableCount: 0

image:
  repository: gcr.io/videocoin-network/profiles
  tag: latest
  pullPolicy: Always

config: {}

service:
  type: ClusterIP
  externalRpcPort: 5004
  internalRpcPort: 5004
  externalManagerRpcPort: 5084
  internalManagerRpcPort: 5084

autoscaler:
  minCount: 1
  maxCount: 10
  targets:
    targetCPUUtilizationPercentage: 70

secrets:
  dbUri: ""
  sentryDsn: ""
